name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-2022

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        id: build-geode
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          combine: true
          # Instructs the runner step to forward its paths directly to the environment
          configure-args: "-DCMAKE_PREFIX_PATH=${{ steps.build-geode.outputs.sdk-path }} -DCMAKE_MODULE_PATH=${{ steps.build-geode.outputs.sdk-path }}/cmake"
